services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=${DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    networks:
      - finbot_network

  finbot-backend:
    container_name: finbot-backend
    build:
      context: .
      dockerfile: Docker/Dockerfile-backend.Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level info
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      PYTHONPATH: /app
      CLICKHOUSE_HOST: ${CLICKHOUSE_HOST}
      CLICKHOUSE_PORT: ${CLICKHOUSE_PORT}
      CLICKHOUSE_DB: ${DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      PROJECT_NAME: ${PROJECT_NAME}
      CORS_ORIGINS: "*"
    env_file:
      - .env
    depends_on:
      - clickhouse
    networks:
      - finbot_network
      
networks:
  finbot_network:
    driver: bridge

volumes:
  clickhouse_data:
